"""Licensed Surface Geometry runtime surfaces (LGE-C1 .. LGE-C5)."""

from taaqqul_slot_geometry.lge._schema_helpers import LGESchemaError
from taaqqul_slot_geometry.lge.c1_surface_token_runtime import (
    LGE_C1_ALLOWED_OUTPUT,
    LGE_C1_FORBIDDEN_OUTPUTS,
    LGE_C1_RANK_CEILING,
    LgeC1SurfaceToken,
    LgeC1TokenFamily,
    emit_lge_c1_surface_token,
)
from taaqqul_slot_geometry.lge.c2_sentence_slot_runtime import (
    LGE_C2_ALLOWED_OUTPUT,
    LGE_C2_FORBIDDEN_OUTPUTS,
    LGE_C2_RANK_CEILING,
    LgeC2RuntimeStatus,
    LgeC2RuntimeVerdict,
    LgeC2SentenceFamily,
    LgeC2SentenceSlot,
    prove_lge_c2_sentence_slot,
)
from taaqqul_slot_geometry.lge.c3_relation_slot_runtime import (
    LGE_C3_ALLOWED_OUTPUT,
    LGE_C3_FORBIDDEN_OUTPUTS,
    LGE_C3_RANK_CEILING,
    LgeC3RelationFamily,
    LgeC3RelationSlot,
    LgeC3RuntimeStatus,
    LgeC3RuntimeVerdict,
    prove_lge_c3_relation_slot,
)
from taaqqul_slot_geometry.lge.c4_inflection_mark_runtime import (
    LGE_C4_ALLOWED_OUTPUT,
    LGE_C4_FORBIDDEN_OUTPUTS,
    LGE_C4_RANK_CEILING,
    LgeC4InflectionSurface,
    LgeC4MarkFamily,
    LgeC4RuntimeStatus,
    LgeC4RuntimeVerdict,
    prove_lge_c4_inflection_surface,
)
from taaqqul_slot_geometry.lge.c5_style_slot_runtime import (
    LGE_C5_ALLOWED_OUTPUT,
    LGE_C5_FORBIDDEN_OUTPUTS,
    LGE_C5_RANK_CEILING,
    LgeC5RuntimeStatus,
    LgeC5RuntimeVerdict,
    LgeC5StyleFamily,
    LgeC5StyleSurface,
    prove_lge_c5_style_surface,
)

__all__ = [
    "LGE_C1_ALLOWED_OUTPUT",
    "LGE_C1_FORBIDDEN_OUTPUTS",
    "LGE_C1_RANK_CEILING",
    "LGE_C2_ALLOWED_OUTPUT",
    "LGE_C2_FORBIDDEN_OUTPUTS",
    "LGE_C2_RANK_CEILING",
    "LGE_C3_ALLOWED_OUTPUT",
    "LGE_C3_FORBIDDEN_OUTPUTS",
    "LGE_C3_RANK_CEILING",
    "LGE_C4_ALLOWED_OUTPUT",
    "LGE_C4_FORBIDDEN_OUTPUTS",
    "LGE_C4_RANK_CEILING",
    "LGE_C5_ALLOWED_OUTPUT",
    "LGE_C5_FORBIDDEN_OUTPUTS",
    "LGE_C5_RANK_CEILING",
    "LGESchemaError",
    "LgeC1SurfaceToken",
    "LgeC1TokenFamily",
    "LgeC2RuntimeStatus",
    "LgeC2RuntimeVerdict",
    "LgeC2SentenceFamily",
    "LgeC2SentenceSlot",
    "LgeC3RelationFamily",
    "LgeC3RelationSlot",
    "LgeC3RuntimeStatus",
    "LgeC3RuntimeVerdict",
    "LgeC4InflectionSurface",
    "LgeC4MarkFamily",
    "LgeC4RuntimeStatus",
    "LgeC4RuntimeVerdict",
    "LgeC5RuntimeStatus",
    "LgeC5RuntimeVerdict",
    "LgeC5StyleFamily",
    "LgeC5StyleSurface",
    "emit_lge_c1_surface_token",
    "prove_lge_c2_sentence_slot",
    "prove_lge_c3_relation_slot",
    "prove_lge_c4_inflection_surface",
    "prove_lge_c5_style_surface",
]
