"""PR-X0R runtime transition contract hooks (no linguistic inference)."""

from taaqqul_slot_geometry.x0r.learning_loop import (
    EuclideanLearningLoopResult,
    EuclideanLearningLoopSchemaError,
    EuclideanLearningState,
    learn_failure,
    learn_success,
    promote_rank_if_evidence_sufficient,
    refine_contract,
)
from taaqqul_slot_geometry.x0r.transition_contract import (
    BranchProof,
    DifferentiatingFeatureProof,
    EuclideanFailureRecord,
    EuclideanGateDecision,
    EuclideanGateStage,
    EuclideanLearningEvidence,
    EuclideanTransitionContract,
    JumpTestContractError,
    JumpTestInput,
    JumpTestResult,
    MinimalCompleteRequirement,
    OriginBranchLinkProof,
    OriginProof,
    QadihCheckStatus,
    RankedBranchPrediction,
    RankForceCeiling,
    ResidualKind,
    TransitionContract,
    TransitionReadinessState,
)

__all__ = [
    "BranchProof",
    "DifferentiatingFeatureProof",
    "EuclideanFailureRecord",
    "EuclideanGateDecision",
    "EuclideanGateStage",
    "EuclideanLearningEvidence",
    "EuclideanLearningLoopResult",
    "EuclideanLearningLoopSchemaError",
    "EuclideanLearningState",
    "EuclideanTransitionContract",
    "JumpTestContractError",
    "JumpTestInput",
    "JumpTestResult",
    "MinimalCompleteRequirement",
    "OriginBranchLinkProof",
    "OriginProof",
    "QadihCheckStatus",
    "RankForceCeiling",
    "RankedBranchPrediction",
    "ResidualKind",
    "TransitionContract",
    "TransitionReadinessState",
    "learn_failure",
    "learn_success",
    "promote_rank_if_evidence_sufficient",
    "refine_contract",
]
