"""``taaqqul_slot_geometry.weight`` — the weight branch.

PR-10 carrier surface + PR-11 path gate + PR-12 μ chain operations
and Ω residual governance + PR-13 minimal WeightFit operation
+ PR-14 lexical / samāʿ / qiyās licensing boundary
+ PR-15 DalOnlyCandidate boundary
+ PR-16 VerbalMadlulCandidate boundary
+ PR-16B unified pre-semantic chain report
+ PR-16C pre-semantic registry contract
+ PR-16C.1 registry closure discipline
+ PR-17 Dal-Madlul binding candidate
+ PR-18 ContractableUnitGeometry boundary
+ PR-F2 Word-Class Formal Definitions (ISM / FI'L / HARF)
+ PR-F3 Built and Reference Formal Definitions (pronouns, demonstratives)
+ PR-F4 Weight Formal Definitions (verbal/nominal/masdar patterns)
+ PR-F5 Inflection Formal Definitions (iʿrāb / bināʾ / triptote / diptote)
+ PR-F6 Contract Slot Formal Definitions (formal agent / object / subject)
+ PR-F7 Composition Pattern Formal Definitions (nominal / verbal / iḍāfa)
+ PR-F8 Formal Style Candidate (khabar/inshāʾ formal only — no meaning)
+ PR-D1 Mufrad Semantic Slot Geometry (geometry only — no dalālah).
+ PR-D1.2 Maqam/Context Boundary Readiness (boundary only — no dalālah).
+ PR-D2 Mutabaqah/Tadammun/Iltizam Candidate (candidates only — no meaning).
+ PR-D3 Mufrad Dalalah Closure (minimum complete closure — no meaning).
+ PR-D4 Relation Closure (relation between two mufrad-closed units — no meaning).
+ PR-20 IfadahCandidate (speech-level closure candidate — never hukm, never meaning).
+ PR-21 HukmCandidate (judgment candidate — never authority, never meaning).
+ PR-21M ManatCandidate (manat candidate — only after hukm; never tanzil, never reality).
+ PR-22 TanzilCandidate (tanzil candidate — presentation-bound; never execution, never authority).
+ PV-A2 MantuqClosureCandidate (mantuq closure — preserved spoken origin; never mafhum).
+ PV-A4 MafhumClosureCandidate (mafhum closure — licensed branch from closed mantuq; never hukm).
+ LAFZI-C1 WadiMadlulContract carrier surface (carriers only — no wadʿī closure).
+ LAFZI-C2 WadKindGate (W1 only — no Wad'iMadlulClosed).
+ LAFZI-C3 WadAuthorityGate (W2 only — no Wad'iMadlulClosed).
+ LAFZI-C4 UsageScopeGate (W3 only — no Wad'iMadlulClosed).
+ LAFZI-C5 MeaningIdentityGate (W4 only — no Wad'iMadlulClosed).
+ LAFZI-C6 TransferMajazGate (W5 only — no Wad'iMadlulClosed).
+ LAFZI-C7 WadiResidualAudit (W6 only — no Wad'iMadlulClosed).
+ LAFZI-C8 Wad'iMadlulClosed -> CoupledDalalahGate integration.
+ LAFZI-D1 CoupledDalalah carrier surface (carrier only — no mutabaqah).

* the pre-weight chain carriers (docs/20 §§4–11) —
  :class:`SyllableCandidate`, :class:`SyllableSequenceCandidate`,
  :class:`WordBoundaryCandidate`, :class:`WordCarrierCandidate`,
  the :class:`PathKind` family with :class:`PathCandidate`,
  :class:`RootStemCandidate`, :class:`LetterStanding` with
  :class:`OriginalExtraMap`, :class:`OperationTraceCandidate`,
  :class:`PreWeightSurface`, :class:`WeightReadinessCandidate`;
* the weight-image carriers (docs/19 §9) — :class:`WeightImage`,
  :class:`Mizan`, :class:`MawzunCandidate`, :class:`SlotAlignment`;
* the pre-weight path gate (PR-11, docs/22) —
  :class:`PathGateProof`, :class:`PathGateState`,
  :class:`PathGateVerdict`, :class:`PreWeightPathGate`;
* the μ chain operations + Ω governance (PR-12, docs/23) —
  :func:`omega_governance`, :func:`mu_seq`, :func:`mu_boundary`,
  :func:`mu_word_carrier`, :func:`mu_root_stem`,
  :func:`mu_original_extra`, :func:`mu_ops`,
  :func:`mu_weight_readiness`;
* the minimal WeightFit operation (PR-13, docs/24) —
  :func:`weigh`, :class:`WeightFitCandidate`,
  :class:`WeightFitResult`, :class:`WeightFitState`;
* the licensing boundary assessment (PR-14, docs/25) —
  :func:`assess_license`, :class:`LicensingBoundaryVerdict`,
  :class:`LicensingBoundaryResult`, :class:`LicensingBoundaryState`,
  :class:`BoundaryEvidence`, :class:`LicenseBoundaryKind`;
* the DalOnlyCandidate boundary (PR-15, docs/26) —
  :func:`prove_dal`, :class:`DalOnlyCandidate`,
  :class:`DalBoundaryVerdict`, :class:`DalBoundaryState`;
* the DAL-A1 carrier-only surface (docs/58) —
  :class:`RawTrace`, :class:`GraphemeCandidate`,
  :class:`LetterIdentity`, :class:`PhoneticRealization`,
  :class:`AtomicSoundUnit`, :class:`DalResidual`,
  :class:`DalAloneClosureSurface`;
* the VerbalMadlulCandidate boundary (PR-16, docs/27) —
  :func:`prove_verbal_madlul`, :class:`VerbalMadlulCandidate`,
  :class:`VerbalMadlulBoundaryVerdict`, :class:`MadlulBoundaryState`;
* the unified pre-semantic chain report (PR-16B, docs/28) —
  :func:`assemble_chain_report`, :class:`PreSemanticChainReport`,
  :class:`ChainReportResult`, :class:`ChainReportState`;
* the pre-semantic registry contract (PR-16C, docs/29) —
  :func:`lookup_registry_entry`, :class:`RegistryDomain`,
  :class:`RegistryEntry`, :class:`RegistryLookupResult`,
  :class:`RegistryLookupState`;
* the registry closure discipline (PR-16C.1, docs/30) —
  :class:`RegistryScope`, :class:`RegistryClosureKind`,
  :class:`RegistryClosureState`, :class:`RegistryClosureVerdict`;
* the Dal-Madlul binding candidate (PR-17, docs/31) —
  :func:`bind_dal_madlul`, :class:`DalMadlulBindingCandidate`,
  :class:`DalMadlulBindingVerdict`, :class:`BindingState`;
* the contractable unit geometry (PR-18, docs/32) —
  :func:`prove_contractable_unit`, :class:`ContractableUnitGeometry`,
  :class:`ContractableUnitVerdict`, :class:`ContractableUnitState`,
  :class:`ContractabilityProfile`;
* the relation candidate boundary (PR-19, docs/33) —
  :func:`prove_relation_candidate`, :class:`RelationCandidate`,
  :class:`RelationVerdict`, :class:`RelationState`;
* the Word-Class Formal Definitions (PR-F2, docs/34 §5) —
  :func:`define_word_class_shape`, :func:`build_word_class_registry`,
  :class:`FormalShapeDomain`, :class:`FormalShapeFamily`,
  :class:`FormalShapeDefinition`, :class:`FormalShapeClosureState`,
  :class:`FormalShapeRegistry`, :class:`WordClassDefinitionVerdict`,
  :class:`WordClassDefinitionState`;
* the Built and Reference Formal Definitions (PR-F3, docs/34 §6) —
  :func:`define_built_reference_shape`,
  :func:`build_built_reference_registry`,
  :class:`BuiltReferenceDefinitionVerdict`,
  :class:`BuiltReferenceDefinitionState`;
* the Weight Formal Definitions (PR-F4, docs/34 §7) —
  :func:`define_weight_pattern_shape`,
  :func:`build_weight_pattern_registry`,
  :class:`WeightPatternDefinitionVerdict`,
  :class:`WeightPatternDefinitionState`;
* the Inflection Formal Definitions (PR-F5, docs/34 §8) —
  :func:`define_inflection_shape`,
  :func:`build_inflection_registry`,
  :class:`InflectionDefinitionVerdict`,
  :class:`InflectionDefinitionState`;
* the Contract Slot Formal Definitions (PR-F6, docs/34 §9) —
  :func:`define_contract_slot_shape`,
  :func:`build_contract_slot_registry`,
  :class:`ContractSlotDefinitionVerdict`,
  :class:`ContractSlotDefinitionState`;
* the Composition Pattern Formal Definitions (PR-F7, docs/34 §10) —
  :func:`define_composition_pattern_shape`,
  :func:`build_composition_pattern_registry`,
  :class:`CompositionPatternDefinitionVerdict`,
  :class:`CompositionPatternDefinitionState`;
* the relation closure (PR-D4, docs/40) —
  :func:`prove_relation_closure`, :class:`RelationClosureCandidate`,
  :class:`RelationClosureVerdict`, :class:`RelationClosureState`,
  :class:`RelationType`.

No alignment operation, no lexicon, and no meaning / agency / hukm /
reality field lives here (docs/14; docs/19 §6; docs/20 §13).
The weight branch never touches the adapter or audit layers.

The hukm layer (PR-21, docs/43) lives here as HukmCandidate — a judgment
candidate that evaluates an IfadahCandidate inside a bounded domain. It
does not produce authority, enforcement, execution, or meaning.

The manat layer (PR-21M, docs/44) lives here as ManatCandidate — a
locus-of-application candidate that identifies where a HukmCandidate might
apply. It does not verify reality, does not produce tanzil, and does not
execute.
"""

from __future__ import annotations

from taaqqul_slot_geometry.weight.carrier_core import (
    BIRTH_RANK_CEILING,
    WeightCarrierBase,
    WeightCarrierSchemaError,
)
from taaqqul_slot_geometry.weight.chain_report import (
    CHAIN_REPORT_RANK_CEILING,
    ChainReportResult,
    ChainReportState,
    PreSemanticChainReport,
    assemble_chain_report,
)
from taaqqul_slot_geometry.weight.contractable_unit_geometry import (
    CONTRACTABLE_UNIT_RANK_CEILING,
    ContractabilityProfile,
    ContractableUnitGeometry,
    ContractableUnitState,
    ContractableUnitVerdict,
    prove_contractable_unit,
)
from taaqqul_slot_geometry.weight.coupled_dalalah import (
    LAFZI_D1_ALLOWED_OUTPUT,
    LAFZI_D1_FORBIDDEN_OUTPUTS,
    LAFZI_D1_RANK_CEILING,
    LAFZI_D1_RESIDUAL_VOCABULARY,
    LAFZI_D2_ALLOWED_OUTPUT,
    LAFZI_D2_FORBIDDEN_OUTPUTS,
    LAFZI_D2_RANK_CEILING,
    CoupledDalalahResidual,
    CoupledDalalahResidualKind,
    CoupledDalalahSurface,
    D1C8HandoffCard,
    MutabaqahGateResult,
    MutabaqahGateState,
    prove_mutabaqah_gate,
)
from taaqqul_slot_geometry.weight.dal_madlul_binding import (
    BINDING_RANK_CEILING,
    BindingState,
    DalMadlulBindingCandidate,
    DalMadlulBindingVerdict,
    bind_dal_madlul,
)
from taaqqul_slot_geometry.weight.dal_only import (
    DAL_A1_FORBIDDEN_OUTPUTS,
    DAL_A1_RANK_CEILING,
    DAL_A1_RESIDUAL_VOCABULARY,
    DAL_BOUNDARY_RANK_CEILING,
    AtomicSoundUnit,
    DalAloneClosureSurface,
    DalBoundaryState,
    DalBoundaryVerdict,
    DalOnlyCandidate,
    DalResidual,
    DalResidualKind,
    GraphemeCandidate,
    LetterIdentity,
    PhoneticRealization,
    RawTrace,
    prove_dal,
)
from taaqqul_slot_geometry.weight.dalalah_candidates import (
    DALALAH_CANDIDATE_RANK_CEILING,
    DalalahCandidateState,
    DalalahCandidateVerdict,
    IltizamCandidate,
    MutabaqahCandidate,
    NecessaryRelationType,
    TadammunCandidate,
    prove_dalalah_candidates,
)
from taaqqul_slot_geometry.weight.formal_shape import (
    ADAH_FORM_DEFINITION,
    ADAH_FORM_FAMILY,
    ADJECTIVE_FORM_DEFINITION,
    ADJECTIVE_FORM_FAMILY,
    BORROWED_NOUN_FORM_DEFINITION,
    BORROWED_NOUN_FORM_FAMILY,
    COMMON_NOUN_FORM_DEFINITION,
    COMMON_NOUN_FORM_FAMILY,
    COMPOUND_NOUN_FORM_DEFINITION,
    COMPOUND_NOUN_FORM_FAMILY,
    CONNECTOR_FORM_DEFINITION,
    CONNECTOR_FORM_FAMILY,
    FIL_DEFINITION,
    FIL_FAMILY,
    FORMAL_SHAPE_RANK_CEILING,
    HARF_DEFINITION,
    HARF_FAMILY,
    ISM_DEFINITION,
    ISM_FAMILY,
    JAMID_NOUN_FORM_DEFINITION,
    JAMID_NOUN_FORM_FAMILY,
    MUSHTAQ_NOUN_FORM_DEFINITION,
    MUSHTAQ_NOUN_FORM_FAMILY,
    PROPER_NAME_FORM_DEFINITION,
    PROPER_NAME_FORM_FAMILY,
    WORD_CLASS_FAMILIES,
    WORD_CLASS_FAMILIES_EXTENDED,
    WORD_CLASS_SUBFAMILIES,
    WORD_CLASS_SUBFAMILY_DEFINITIONS,
    FormalShapeClosureState,
    FormalShapeDefinition,
    FormalShapeDomain,
    FormalShapeFamily,
    FormalShapeRegistry,
    WordClassDefinitionState,
    WordClassDefinitionVerdict,
    build_word_class_registry,
    define_word_class_shape,
)
from taaqqul_slot_geometry.weight.formal_shape_built_reference import (
    BUILT_REFERENCE_FAMILIES,
    CONDITIONAL_DEFINITION,
    CONDITIONAL_FAMILY,
    DEMONSTRATIVE_DEFINITION,
    DEMONSTRATIVE_FAMILY,
    INTERROGATIVE_DEFINITION,
    INTERROGATIVE_FAMILY,
    PERSONAL_PRONOUN_DEFINITION,
    PERSONAL_PRONOUN_FAMILY,
    RELATIVE_PRONOUN_DEFINITION,
    RELATIVE_PRONOUN_FAMILY,
    BuiltReferenceDefinitionState,
    BuiltReferenceDefinitionVerdict,
    build_built_reference_registry,
    define_built_reference_shape,
)
from taaqqul_slot_geometry.weight.formal_shape_composition import (
    ATIF_DEFINITION,
    ATIF_FAMILY,
    BADAL_DEFINITION,
    BADAL_FAMILY,
    COMPOSITION_PATTERN_FAMILIES,
    IDAFA_DEFINITION,
    IDAFA_FAMILY,
    NOMINAL_SENTENCE_DEFINITION,
    NOMINAL_SENTENCE_FAMILY,
    SIFA_MAWSUF_DEFINITION,
    SIFA_MAWSUF_FAMILY,
    VERBAL_SENTENCE_DEFINITION,
    VERBAL_SENTENCE_FAMILY,
    CompositionPatternDefinitionState,
    CompositionPatternDefinitionVerdict,
    build_composition_pattern_registry,
    define_composition_pattern_shape,
)
from taaqqul_slot_geometry.weight.formal_shape_contract_slot import (
    CONTRACT_SLOT_FAMILIES,
    FORMAL_GENITIVE_SLOT_DEFINITION,
    FORMAL_GENITIVE_SLOT_FAMILY,
    FORMAL_OBJECT_SLOT_DEFINITION,
    FORMAL_OBJECT_SLOT_FAMILY,
    FORMAL_PREDICATE_SLOT_DEFINITION,
    FORMAL_PREDICATE_SLOT_FAMILY,
    FORMAL_QUALIFIER_SLOT_DEFINITION,
    FORMAL_QUALIFIER_SLOT_FAMILY,
    FORMAL_SPECIFICATION_SLOT_DEFINITION,
    FORMAL_SPECIFICATION_SLOT_FAMILY,
    FORMAL_STATE_SLOT_DEFINITION,
    FORMAL_STATE_SLOT_FAMILY,
    FORMAL_SUBJECT_SLOT_DEFINITION,
    FORMAL_SUBJECT_SLOT_FAMILY,
    FORMAL_TOPIC_SLOT_DEFINITION,
    FORMAL_TOPIC_SLOT_FAMILY,
    ContractSlotDefinitionState,
    ContractSlotDefinitionVerdict,
    build_contract_slot_registry,
    define_contract_slot_shape,
)
from taaqqul_slot_geometry.weight.formal_shape_inflection import (
    DECLENSION_BLOCK_FORM_DEFINITION,
    DECLENSION_BLOCK_FORM_FAMILY,
    DIPTOTE_FORM_DEFINITION,
    DIPTOTE_FORM_FAMILY,
    ESTIMATED_MARK_FORM_DEFINITION,
    ESTIMATED_MARK_FORM_FAMILY,
    GOVERNANCE_EFFECT_DEFERRED_FORM_DEFINITION,
    GOVERNANCE_EFFECT_DEFERRED_FORM_FAMILY,
    INFLECTION_FAMILIES,
    JARR_MARK_FORM_DEFINITION,
    JARR_MARK_FORM_FAMILY,
    JAZM_MARK_FORM_DEFINITION,
    JAZM_MARK_FORM_FAMILY,
    MABNI_FORM_DEFINITION,
    MABNI_FORM_FAMILY,
    MURAB_FORM_DEFINITION,
    MURAB_FORM_FAMILY,
    NASB_MARK_FORM_DEFINITION,
    NASB_MARK_FORM_FAMILY,
    ORIGINAL_MARK_FORM_DEFINITION,
    ORIGINAL_MARK_FORM_FAMILY,
    RAF_MARK_FORM_DEFINITION,
    RAF_MARK_FORM_FAMILY,
    SUBSIDIARY_MARK_FORM_DEFINITION,
    SUBSIDIARY_MARK_FORM_FAMILY,
    InflectionDefinitionState,
    InflectionDefinitionVerdict,
    build_inflection_registry,
    define_inflection_shape,
)
from taaqqul_slot_geometry.weight.formal_shape_weight_pattern import (
    FAIL_FORM_DEFINITION,
    FAIL_FORM_FAMILY,
    GENDERED_WEIGHT_FORM_DEFINITION,
    GENDERED_WEIGHT_FORM_FAMILY,
    INSTRUMENT_FORM_DEFINITION,
    INSTRUMENT_FORM_FAMILY,
    JAMID_WEIGHT_FORM_DEFINITION,
    JAMID_WEIGHT_FORM_FAMILY,
    MAFUL_FORM_DEFINITION,
    MAFUL_FORM_FAMILY,
    MASDAR_MAZID_PATTERN_DEFINITION,
    MASDAR_MAZID_PATTERN_FAMILY,
    MASDAR_MUJARRAD_PATTERN_DEFINITION,
    MASDAR_MUJARRAD_PATTERN_FAMILY,
    NOMINAL_DERIVED_PATTERN_DEFINITION,
    NOMINAL_DERIVED_PATTERN_FAMILY,
    SIFAH_MUSHABBAHA_FORM_DEFINITION,
    SIFAH_MUSHABBAHA_FORM_FAMILY,
    TIME_PLACE_FORM_DEFINITION,
    TIME_PLACE_FORM_FAMILY,
    VERBAL_MAZID_PATTERN_DEFINITION,
    VERBAL_MAZID_PATTERN_FAMILY,
    VERBAL_MUJARRAD_PATTERN_DEFINITION,
    VERBAL_MUJARRAD_PATTERN_FAMILY,
    WEIGHT_PATTERN_FAMILIES,
    WeightPatternDefinitionState,
    WeightPatternDefinitionVerdict,
    build_weight_pattern_registry,
    define_weight_pattern_shape,
)
from taaqqul_slot_geometry.weight.formal_style_candidate import (
    FORMAL_STYLE_DEFINITIONS,
    FORMAL_STYLE_FAMILIES,
    FormalStyleCandidate,
    FormalStyleFamily,
    FormalStyleState,
    FormalStyleVerdict,
    prove_formal_style_candidate,
)
from taaqqul_slot_geometry.weight.hukm_candidate import (
    HUKM_RANK_CEILING,
    EvaluationDomain,
    HukmCandidate,
    HukmState,
    HukmVerdict,
    prove_hukm_candidate,
)
from taaqqul_slot_geometry.weight.ifadah_candidate import (
    IFADAH_RANK_CEILING,
    IfadahCandidate,
    IfadahState,
    IfadahVerdict,
    SpeechForceKind,
    prove_ifadah_candidate,
)
from taaqqul_slot_geometry.weight.licensing_boundary import (
    LICENSE_BOUNDARY_RANK_CEILING,
    BoundaryEvidence,
    LicenseBoundaryKind,
    LicensingBoundaryResult,
    LicensingBoundaryState,
    LicensingBoundaryVerdict,
    assess_license,
)
from taaqqul_slot_geometry.weight.mafhum_closure import (
    MAFHUM_RANK_CEILING,
    MafhumBranchType,
    MafhumClosureCandidate,
    MafhumClosureState,
    MafhumClosureVerdict,
    prove_mafhum_closure,
)
from taaqqul_slot_geometry.weight.manat_candidate import (
    MANAT_RANK_CEILING,
    ManatCandidate,
    ManatMode,
    ManatState,
    ManatVerdict,
    prove_manat_candidate,
)
from taaqqul_slot_geometry.weight.mantuq_closure import (
    MANTUQ_RANK_CEILING,
    MantuqClosureCandidate,
    MantuqClosureState,
    MantuqClosureVerdict,
    prove_mantuq_closure,
)
from taaqqul_slot_geometry.weight.mu_chain import (
    MU_CHAIN_RANK_CEILING,
    MuStepResult,
    MuStepState,
    OmegaGovernanceState,
    ResidualGovernanceVerdict,
    mu_boundary,
    mu_ops,
    mu_original_extra,
    mu_root_stem,
    mu_seq,
    mu_weight_readiness,
    mu_word_carrier,
    omega_governance,
)
from taaqqul_slot_geometry.weight.mufrad_dalalah_closure import (
    MUFRAD_DALALAH_CLOSURE_RANK_CEILING,
    MufradDalalahClosureCandidate,
    MufradDalalahClosureState,
    MufradDalalahClosureVerdict,
    prove_mufrad_dalalah_closure,
)
from taaqqul_slot_geometry.weight.mufrad_semantic_slot_geometry import (
    SEMANTIC_CATEGORIES,
    SEMANTIC_SLOT_GEOMETRY_RANK_CEILING,
    BranchLinkCandidate,
    KulliJuziiAxis,
    KulliJuziiAxisVerdict,
    MufradSemanticSlotGeometryVerdict,
    MufradSemanticState,
    ParticularitySource,
    PerUnitFormalProfileClosure,
    SemanticCategory,
    SemanticSlotFrame,
    WadEvidenceCarrier,
    WadEvidenceType,
    WadOriginDomain,
    prove_mufrad_semantic_slot_geometry,
)
from taaqqul_slot_geometry.weight.path_gate import (
    PATH_GATE_RANK_CEILING,
    PathGateProof,
    PathGateState,
    PathGateVerdict,
    PreWeightPathGate,
)
from taaqqul_slot_geometry.weight.pre_weight import (
    LetterStanding,
    OperationTraceCandidate,
    OriginalExtraMap,
    PathCandidate,
    PathKind,
    PreWeightSurface,
    RootStemCandidate,
    SyllableCandidate,
    SyllableSequenceCandidate,
    WeightReadinessCandidate,
    WordBoundaryCandidate,
    WordCarrierCandidate,
)
from taaqqul_slot_geometry.weight.registry_closure import (
    REGISTRY_CLOSURE_RANK_CEILING,
    RegistryClosureKind,
    RegistryClosureState,
    RegistryClosureVerdict,
    RegistryScope,
)
from taaqqul_slot_geometry.weight.registry_contract import (
    REGISTRY_RANK_CEILING,
    RegistryDomain,
    RegistryEntry,
    RegistryLookupResult,
    RegistryLookupState,
    lookup_registry_entry,
)
from taaqqul_slot_geometry.weight.relation_candidate import (
    RELATION_CANDIDATE_RANK_CEILING,
    RelationCandidate,
    RelationState,
    RelationVerdict,
    prove_relation_candidate,
)
from taaqqul_slot_geometry.weight.relation_closure import (
    RELATION_CLOSURE_RANK_CEILING,
    RelationClosureCandidate,
    RelationClosureState,
    RelationClosureVerdict,
    RelationType,
    prove_relation_closure,
)
from taaqqul_slot_geometry.weight.tanzil_candidate import (
    TANZIL_RANK_CEILING,
    TanzilCandidate,
    TanzilPresentationEnvelope,
    TanzilState,
    TanzilVerdict,
    prove_tanzil_candidate,
)
from taaqqul_slot_geometry.weight.verbal_madlul import (
    MADLUL_BOUNDARY_RANK_CEILING,
    MadlulBoundaryState,
    VerbalMadlulBoundaryVerdict,
    VerbalMadlulCandidate,
    prove_verbal_madlul,
)
from taaqqul_slot_geometry.weight.wadi_c8_integration import (
    WADI_C8_ALLOWED_OUTPUT,
    WADI_C8_FORBIDDEN_OUTPUTS,
    WADI_C8_RANK_CEILING,
    CoupledDalalahGateResult,
    WadiMadlulClosed,
    WadiMadlulState,
    WadiMadlulVerdict,
    WadiStopGateResult,
    prove_coupled_dalalah_gate,
    prove_wadi_madlul,
    prove_wadi_stop_gate,
    prove_wadi_to_coupled_dalalah,
)
from taaqqul_slot_geometry.weight.wadi_madlul import (
    WADI_C1_FORBIDDEN_OUTPUTS,
    WADI_C1_RANK_CEILING,
    WADI_C1_RESIDUAL_VOCABULARY,
    WADI_C2_ALLOWED_OUTPUT,
    WADI_C2_RANK_CEILING,
    WADI_C3_ALLOWED_OUTPUT,
    WADI_C3_RANK_CEILING,
    WADI_C4_ALLOWED_OUTPUT,
    WADI_C4_RANK_CEILING,
    WADI_C5_ALLOWED_OUTPUT,
    WADI_C5_RANK_CEILING,
    WADI_C6_ALLOWED_OUTPUT,
    WADI_C6_RANK_CEILING,
    WADI_C7_ALLOWED_OUTPUT,
    WADI_C7_RANK_CEILING,
    MeaningIdentity,
    MeaningIdentityGateResult,
    MeaningIdentityGateState,
    MeaningIdentityKind,
    TransferMajazGateResult,
    TransferMajazGateState,
    TransferOrMajazKind,
    TransferOrMajazStatus,
    UsageScope,
    UsageScopeGateResult,
    UsageScopeGateState,
    UsageScopeKind,
    WadAuthority,
    WadAuthorityFamily,
    WadAuthorityGateResult,
    WadAuthorityGateState,
    WadiMadlulContract,
    WadiResidual,
    WadiResidualAuditResult,
    WadiResidualAuditState,
    WadiResidualKind,
    WadKind,
    WadKindGateResult,
    WadKindGateState,
    prove_meaning_identity_gate,
    prove_transfer_majaz_gate,
    prove_usage_scope_gate,
    prove_wad_authority_gate,
    prove_wad_kind_gate,
    prove_wadi_residual_audit,
)
from taaqqul_slot_geometry.weight.weight_fit import (
    WEIGHT_FIT_RANK_CEILING,
    WeightFitCandidate,
    WeightFitResult,
    WeightFitState,
    weigh,
)
from taaqqul_slot_geometry.weight.weight_image import (
    PATTERN_SPACE,
    MawzunCandidate,
    Mizan,
    SlotAlignment,
    WeightImage,
)

__all__ = [
    "ADAH_FORM_DEFINITION",
    "ADAH_FORM_FAMILY",
    "ADJECTIVE_FORM_DEFINITION",
    "ADJECTIVE_FORM_FAMILY",
    "ATIF_DEFINITION",
    "ATIF_FAMILY",
    "BADAL_DEFINITION",
    "BADAL_FAMILY",
    "BINDING_RANK_CEILING",
    "BIRTH_RANK_CEILING",
    "BORROWED_NOUN_FORM_DEFINITION",
    "BORROWED_NOUN_FORM_FAMILY",
    "BUILT_REFERENCE_FAMILIES",
    "BuiltReferenceDefinitionState",
    "BuiltReferenceDefinitionVerdict",
    "CHAIN_REPORT_RANK_CEILING",
    "COMMON_NOUN_FORM_DEFINITION",
    "COMMON_NOUN_FORM_FAMILY",
    "COMPOSITION_PATTERN_FAMILIES",
    "CompositionPatternDefinitionState",
    "CompositionPatternDefinitionVerdict",
    "COMPOUND_NOUN_FORM_DEFINITION",
    "COMPOUND_NOUN_FORM_FAMILY",
    "CONDITIONAL_DEFINITION",
    "CONDITIONAL_FAMILY",
    "CONNECTOR_FORM_DEFINITION",
    "CONNECTOR_FORM_FAMILY",
    "CONTRACTABLE_UNIT_RANK_CEILING",
    "CONTRACT_SLOT_FAMILIES",
    "ContractSlotDefinitionState",
    "ContractSlotDefinitionVerdict",
    "DAL_A1_FORBIDDEN_OUTPUTS",
    "DAL_A1_RANK_CEILING",
    "DAL_A1_RESIDUAL_VOCABULARY",
    "DALALAH_CANDIDATE_RANK_CEILING",
    "DAL_BOUNDARY_RANK_CEILING",
    "AtomicSoundUnit",
    "DalAloneClosureSurface",
    "DalalahCandidateState",
    "DalalahCandidateVerdict",
    "DalResidual",
    "DalResidualKind",
    "DECLENSION_BLOCK_FORM_DEFINITION",
    "DECLENSION_BLOCK_FORM_FAMILY",
    "DEMONSTRATIVE_DEFINITION",
    "DEMONSTRATIVE_FAMILY",
    "DIPTOTE_FORM_DEFINITION",
    "DIPTOTE_FORM_FAMILY",
    "ESTIMATED_MARK_FORM_DEFINITION",
    "ESTIMATED_MARK_FORM_FAMILY",
    "FAIL_FORM_DEFINITION",
    "FAIL_FORM_FAMILY",
    "FIL_DEFINITION",
    "FIL_FAMILY",
    "FORMAL_GENITIVE_SLOT_DEFINITION",
    "FORMAL_GENITIVE_SLOT_FAMILY",
    "FORMAL_OBJECT_SLOT_DEFINITION",
    "FORMAL_OBJECT_SLOT_FAMILY",
    "FORMAL_PREDICATE_SLOT_DEFINITION",
    "FORMAL_PREDICATE_SLOT_FAMILY",
    "FORMAL_QUALIFIER_SLOT_DEFINITION",
    "FORMAL_QUALIFIER_SLOT_FAMILY",
    "FORMAL_SHAPE_RANK_CEILING",
    "FORMAL_SPECIFICATION_SLOT_DEFINITION",
    "FORMAL_SPECIFICATION_SLOT_FAMILY",
    "FORMAL_STATE_SLOT_DEFINITION",
    "FORMAL_STATE_SLOT_FAMILY",
    "FORMAL_SUBJECT_SLOT_DEFINITION",
    "FORMAL_SUBJECT_SLOT_FAMILY",
    "FORMAL_TOPIC_SLOT_DEFINITION",
    "FORMAL_TOPIC_SLOT_FAMILY",
    "GENDERED_WEIGHT_FORM_DEFINITION",
    "GENDERED_WEIGHT_FORM_FAMILY",
    "GOVERNANCE_EFFECT_DEFERRED_FORM_DEFINITION",
    "GOVERNANCE_EFFECT_DEFERRED_FORM_FAMILY",
    "HARF_DEFINITION",
    "HARF_FAMILY",
    "HUKM_RANK_CEILING",
    "HukmCandidate",
    "HukmState",
    "HukmVerdict",
    "IDAFA_DEFINITION",
    "IDAFA_FAMILY",
    "IFADAH_RANK_CEILING",
    "INFLECTION_FAMILIES",
    "INSTRUMENT_FORM_DEFINITION",
    "INSTRUMENT_FORM_FAMILY",
    "INTERROGATIVE_DEFINITION",
    "INTERROGATIVE_FAMILY",
    "ISM_DEFINITION",
    "ISM_FAMILY",
    "IfadahCandidate",
    "IfadahState",
    "IfadahVerdict",
    "IltizamCandidate",
    "InflectionDefinitionState",
    "InflectionDefinitionVerdict",
    "JAMID_NOUN_FORM_DEFINITION",
    "JAMID_NOUN_FORM_FAMILY",
    "JAMID_WEIGHT_FORM_DEFINITION",
    "JAMID_WEIGHT_FORM_FAMILY",
    "JARR_MARK_FORM_DEFINITION",
    "JARR_MARK_FORM_FAMILY",
    "JAZM_MARK_FORM_DEFINITION",
    "JAZM_MARK_FORM_FAMILY",
    "GraphemeCandidate",
    "LetterIdentity",
    "LICENSE_BOUNDARY_RANK_CEILING",
    "MABNI_FORM_DEFINITION",
    "MABNI_FORM_FAMILY",
    "MADLUL_BOUNDARY_RANK_CEILING",
    "MAFUL_FORM_DEFINITION",
    "MAFUL_FORM_FAMILY",
    "MAFHUM_RANK_CEILING",
    "MafhumBranchType",
    "MafhumClosureCandidate",
    "MafhumClosureState",
    "MafhumClosureVerdict",
    "MANAT_RANK_CEILING",
    "MANTUQ_RANK_CEILING",
    "ManatCandidate",
    "ManatMode",
    "ManatState",
    "ManatVerdict",
    "MantuqClosureCandidate",
    "MantuqClosureState",
    "MantuqClosureVerdict",
    "MASDAR_MAZID_PATTERN_DEFINITION",
    "MASDAR_MAZID_PATTERN_FAMILY",
    "MASDAR_MUJARRAD_PATTERN_DEFINITION",
    "MASDAR_MUJARRAD_PATTERN_FAMILY",
    "MU_CHAIN_RANK_CEILING",
    "MUFRAD_DALALAH_CLOSURE_RANK_CEILING",
    "MURAB_FORM_DEFINITION",
    "MURAB_FORM_FAMILY",
    "MUSHTAQ_NOUN_FORM_DEFINITION",
    "MUSHTAQ_NOUN_FORM_FAMILY",
    "NASB_MARK_FORM_DEFINITION",
    "NASB_MARK_FORM_FAMILY",
    "NOMINAL_DERIVED_PATTERN_DEFINITION",
    "NOMINAL_DERIVED_PATTERN_FAMILY",
    "NOMINAL_SENTENCE_DEFINITION",
    "NOMINAL_SENTENCE_FAMILY",
    "ORIGINAL_MARK_FORM_DEFINITION",
    "ORIGINAL_MARK_FORM_FAMILY",
    "PATH_GATE_RANK_CEILING",
    "PATTERN_SPACE",
    "PERSONAL_PRONOUN_DEFINITION",
    "PERSONAL_PRONOUN_FAMILY",
    "PhoneticRealization",
    "PROPER_NAME_FORM_DEFINITION",
    "PROPER_NAME_FORM_FAMILY",
    "RAF_MARK_FORM_DEFINITION",
    "RAF_MARK_FORM_FAMILY",
    "RawTrace",
    "REGISTRY_CLOSURE_RANK_CEILING",
    "REGISTRY_RANK_CEILING",
    "RELATION_CANDIDATE_RANK_CEILING",
    "RELATION_CLOSURE_RANK_CEILING",
    "RELATIVE_PRONOUN_DEFINITION",
    "RELATIVE_PRONOUN_FAMILY",
    "SIFA_MAWSUF_DEFINITION",
    "SIFA_MAWSUF_FAMILY",
    "SIFAH_MUSHABBAHA_FORM_DEFINITION",
    "SIFAH_MUSHABBAHA_FORM_FAMILY",
    "SUBSIDIARY_MARK_FORM_DEFINITION",
    "SUBSIDIARY_MARK_FORM_FAMILY",
    "TIME_PLACE_FORM_DEFINITION",
    "TIME_PLACE_FORM_FAMILY",
    "VERBAL_MAZID_PATTERN_DEFINITION",
    "VERBAL_MAZID_PATTERN_FAMILY",
    "VERBAL_MUJARRAD_PATTERN_DEFINITION",
    "VERBAL_MUJARRAD_PATTERN_FAMILY",
    "VERBAL_SENTENCE_DEFINITION",
    "VERBAL_SENTENCE_FAMILY",
    "WEIGHT_FIT_RANK_CEILING",
    "WEIGHT_PATTERN_FAMILIES",
    "WORD_CLASS_FAMILIES",
    "WORD_CLASS_FAMILIES_EXTENDED",
    "WORD_CLASS_SUBFAMILIES",
    "WORD_CLASS_SUBFAMILY_DEFINITIONS",
    "BindingState",
    "BoundaryEvidence",
    "BranchLinkCandidate",
    "ChainReportResult",
    "ChainReportState",
    "ContractabilityProfile",
    "ContractableUnitGeometry",
    "ContractableUnitState",
    "ContractableUnitVerdict",
    "DalBoundaryState",
    "DalBoundaryVerdict",
    "DalMadlulBindingCandidate",
    "DalMadlulBindingVerdict",
    "DalOnlyCandidate",
    "EvaluationDomain",
    "FORMAL_STYLE_DEFINITIONS",
    "FORMAL_STYLE_FAMILIES",
    "FormalShapeClosureState",
    "FormalShapeDefinition",
    "FormalShapeDomain",
    "FormalShapeFamily",
    "FormalShapeRegistry",
    "FormalStyleCandidate",
    "FormalStyleFamily",
    "FormalStyleState",
    "FormalStyleVerdict",
    "KulliJuziiAxis",
    "KulliJuziiAxisVerdict",
    "LetterStanding",
    "LicenseBoundaryKind",
    "LicensingBoundaryResult",
    "LicensingBoundaryState",
    "LicensingBoundaryVerdict",
    "MadlulBoundaryState",
    "MawzunCandidate",
    "MeaningIdentity",
    "MeaningIdentityKind",
    "Mizan",
    "MufradDalalahClosureCandidate",
    "MufradDalalahClosureState",
    "MufradDalalahClosureVerdict",
    "MufradSemanticSlotGeometryVerdict",
    "MufradSemanticState",
    "MuStepResult",
    "MuStepState",
    "MutabaqahCandidate",
    "NecessaryRelationType",
    "OmegaGovernanceState",
    "OperationTraceCandidate",
    "OriginalExtraMap",
    "ParticularitySource",
    "PathCandidate",
    "PathGateProof",
    "PathGateState",
    "PathGateVerdict",
    "PathKind",
    "PerUnitFormalProfileClosure",
    "PreSemanticChainReport",
    "PreWeightPathGate",
    "PreWeightSurface",
    "RegistryClosureKind",
    "RegistryClosureState",
    "RegistryClosureVerdict",
    "RegistryDomain",
    "RegistryEntry",
    "RegistryLookupResult",
    "RegistryLookupState",
    "RegistryScope",
    "RelationCandidate",
    "RelationClosureCandidate",
    "RelationClosureState",
    "RelationClosureVerdict",
    "RelationState",
    "RelationType",
    "RelationVerdict",
    "ResidualGovernanceVerdict",
    "RootStemCandidate",
    "SEMANTIC_CATEGORIES",
    "SEMANTIC_SLOT_GEOMETRY_RANK_CEILING",
    "SemanticCategory",
    "SemanticSlotFrame",
    "SlotAlignment",
    "SpeechForceKind",
    "SyllableCandidate",
    "SyllableSequenceCandidate",
    "TadammunCandidate",
    "TANZIL_RANK_CEILING",
    "TanzilCandidate",
    "TanzilPresentationEnvelope",
    "TanzilState",
    "TanzilVerdict",
    "TransferOrMajazKind",
    "TransferOrMajazStatus",
    "UsageScope",
    "UsageScopeGateResult",
    "UsageScopeGateState",
    "UsageScopeKind",
    "VerbalMadlulBoundaryVerdict",
    "VerbalMadlulCandidate",
    "WADI_C1_FORBIDDEN_OUTPUTS",
    "WADI_C1_RANK_CEILING",
    "WADI_C1_RESIDUAL_VOCABULARY",
    "WADI_C2_ALLOWED_OUTPUT",
    "WADI_C2_RANK_CEILING",
    "WADI_C3_ALLOWED_OUTPUT",
    "WADI_C3_RANK_CEILING",
    "WADI_C4_ALLOWED_OUTPUT",
    "WADI_C4_RANK_CEILING",
    "WADI_C5_ALLOWED_OUTPUT",
    "WADI_C5_RANK_CEILING",
    "WADI_C6_ALLOWED_OUTPUT",
    "WADI_C6_RANK_CEILING",
    "WADI_C7_ALLOWED_OUTPUT",
    "WADI_C7_RANK_CEILING",
    "WADI_C8_ALLOWED_OUTPUT",
    "WADI_C8_FORBIDDEN_OUTPUTS",
    "WADI_C8_RANK_CEILING",
    "MeaningIdentity",
    "MeaningIdentityGateResult",
    "MeaningIdentityGateState",
    "MeaningIdentityKind",
    "TransferMajazGateResult",
    "TransferMajazGateState",
    "TransferOrMajazKind",
    "TransferOrMajazStatus",
    "UsageScope",
    "UsageScopeGateResult",
    "UsageScopeGateState",
    "UsageScopeKind",
    "WadAuthority",
    "WadAuthorityFamily",
    "WadAuthorityGateResult",
    "WadAuthorityGateState",
    "WadEvidenceCarrier",
    "WadEvidenceType",
    "WadKind",
    "WadKindGateResult",
    "WadKindGateState",
    "WadOriginDomain",
    "WadiMadlulContract",
    "WadiMadlulClosed",
    "WadiMadlulState",
    "WadiMadlulVerdict",
    "WadiResidualAuditResult",
    "WadiResidualAuditState",
    "WadiResidual",
    "WadiResidualKind",
    "WadiStopGateResult",
    "CoupledDalalahGateResult",
    "D1C8HandoffCard",
    "CoupledDalalahSurface",
    "CoupledDalalahResidualKind",
    "CoupledDalalahResidual",
    "LAFZI_D1_RESIDUAL_VOCABULARY",
    "LAFZI_D1_RANK_CEILING",
    "LAFZI_D1_FORBIDDEN_OUTPUTS",
    "LAFZI_D1_ALLOWED_OUTPUT",
    "LAFZI_D2_RANK_CEILING",
    "LAFZI_D2_FORBIDDEN_OUTPUTS",
    "LAFZI_D2_ALLOWED_OUTPUT",
    "MutabaqahGateResult",
    "MutabaqahGateState",
    "WeightCarrierBase",
    "WeightCarrierSchemaError",
    "WeightFitCandidate",
    "WeightFitResult",
    "WeightFitState",
    "WeightImage",
    "WeightPatternDefinitionState",
    "WeightPatternDefinitionVerdict",
    "WeightReadinessCandidate",
    "WordBoundaryCandidate",
    "prove_wad_kind_gate",
    "prove_wad_authority_gate",
    "prove_usage_scope_gate",
    "prove_meaning_identity_gate",
    "prove_transfer_majaz_gate",
    "prove_wadi_residual_audit",
    "prove_wadi_madlul",
    "prove_wadi_stop_gate",
    "prove_coupled_dalalah_gate",
    "prove_wadi_to_coupled_dalalah",
    "prove_mutabaqah_gate",
    "WordCarrierCandidate",
    "WordClassDefinitionState",
    "WordClassDefinitionVerdict",
    "assemble_chain_report",
    "assess_license",
    "bind_dal_madlul",
    "build_built_reference_registry",
    "build_composition_pattern_registry",
    "build_contract_slot_registry",
    "build_inflection_registry",
    "build_weight_pattern_registry",
    "build_word_class_registry",
    "define_built_reference_shape",
    "define_composition_pattern_shape",
    "define_contract_slot_shape",
    "define_inflection_shape",
    "define_weight_pattern_shape",
    "define_word_class_shape",
    "lookup_registry_entry",
    "mu_boundary",
    "mu_ops",
    "mu_original_extra",
    "mu_root_stem",
    "mu_seq",
    "mu_weight_readiness",
    "mu_word_carrier",
    "omega_governance",
    "prove_contractable_unit",
    "prove_dal",
    "prove_dalalah_candidates",
    "prove_formal_style_candidate",
    "prove_hukm_candidate",
    "prove_ifadah_candidate",
    "prove_mafhum_closure",
    "prove_manat_candidate",
    "prove_mantuq_closure",
    "prove_mufrad_dalalah_closure",
    "prove_mufrad_semantic_slot_geometry",
    "prove_relation_candidate",
    "prove_relation_closure",
    "prove_tanzil_candidate",
    "prove_verbal_madlul",
    "weigh",
]
